### ISSUE TITLE
Improve sharder to work with very large files

### ISSUE THREAD

**Issue by lakewik** [storj/storj-python-sdk#109] opened 2017-04-30 12:43 UTC
How the sharder hangs with very large file. (example 43 GB)
https://github.com/lakewik/storj-gui-client/issues/49

**Comment by lakewik** [comment] 2017-05-01 05:53
https://github.com/Storj/storj-python-sdk/issues/109

**Comment by steenzout** [comment] 2017-05-01 16:12
```
QPixmap: It is not safe to use pixmaps outside the GUI thread
Exception in thread Thread-195:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "storj-gui-client\UI\file_upload.py", line 916, in file_upload_begin
  File "site-packages\storj\model.py", line 692, in __init__
  File "site-packages\storj\model.py", line 710, in filepath
  File "site-packages\storj\model.py", line 834, in _make_shards
OverflowError: Python int too large to convert to C long

Exception in thread Thread-192:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "storj-gui-client\UI\file_upload.py", line 916, in file_upload_begin
  File "site-packages\storj\model.py", line 692, in __init__
  File "site-packages\storj\model.py", line 710, in filepath
  File "site-packages\storj\model.py", line 834, in _make_shards
OverflowError: Python int too large to convert to C long
```

**Comment by lakewik** [comment] 2017-05-01 16:45
```
total_bytes += numpy.int32(len(data))
                
                inc = numpy.int32(len(data))
``` instead of `total_bytes += len(data)
                
                inc = len(data)` maybe solution

**Comment by steenzout** [comment] 2017-05-01 18:20
@lakewik which means you'd add `numpy` as a dependency...

**Comment by steenzout** [comment] 2017-05-01 18:23
is it just a Windows thing?

[stackoverflow](http://stackoverflow.com/questions/38314118/overflowerror-python-int-too-large-to-convert-to-c-long-on-windows-but-not-ma)

**Comment by lakewik** [comment] 2017-05-01 18:25
@steenzout I don't know, i not tested this yet on linux, but i'm going to do it, I will send today binary of my GUI containing this fix to @MeijeSibbel and he will check if all is ok

**Comment by steenzout** [comment] 2017-05-01 18:32
I don't think it's a good idea to have `numpy` as a dependency.

*note*: I think the problem is on the other side of the operand.

have you tried doing just `print len(data)` and seeing if it throws an error?

I'm saying this because `chunksz` should be relatively small (`< sys.maxsize`) when compared with whole file size so `len(data)` should always be ok.
`total_bytes` however is always incrementing so if the file size is `> sys.maxsize` then I can see this error being thrown.

if this is the case you may be able to just drop `total_bytes` variable.

**Comment by steenzout** [comment] 2017-05-04 23:11
```
Login from credentials xml file
2017-05-04 21:51:05,477 DEBUG Login from credentials xml file
testlogin, StorjEngine
2017-05-04 21:51:05,480 DEBUG testlogin, StorjEngine
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QObject::startTimer: timers cannot be started from another thread
zpliku d894cfc6ee576b33b56f4467eac24ca5774245cc580185b895273d90b937aaa1
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "storj-gui-client\UI\file_upload.py", line 965, in file_upload_begin
  File "site-packages\storj\model.py", line 681, in __init__
  File "site-packages\storj\model.py", line 699, in filepath
  File "site-packages\storj\model.py", line 819, in _make_shards
OverflowError: Python int too large to convert to C long
```

**Comment by enricobacis** [comment] 2017-05-09 17:23
I believe the recent change introduced with the TemporaryFiles (PR #119) should fix this issue, at least at downloader side.

**Comment by RichardLitt** [comment] 2018-10-30 12:02
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!

**Closed by RichardLitt** 2018-10-30 12:02 UTC
Labels: bug, improvement
